# Generated by Django 5.2.5 on 2025-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
